2022-07-06 08:39:59,462 INFO    MainThread:48303 [internal.py:wandb_internal():93] W&B internal server running at pid: 48303, started at: 2022-07-06 08:39:59.460555
2022-07-06 08:39:59,465 INFO    WriterThread:48303 [datastore.py:open_for_write():75] open: /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_083958-1yhv5uf4/run-1yhv5uf4.wandb
2022-07-06 08:39:59,472 DEBUG   SenderThread:48303 [sender.py:send():236] send: header
2022-07-06 08:39:59,472 DEBUG   SenderThread:48303 [sender.py:send():236] send: run
2022-07-06 08:39:59,655 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: check_version
2022-07-06 08:39:59,667 INFO    SenderThread:48303 [dir_watcher.py:__init__():216] watching files in: /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_083958-1yhv5uf4/files
2022-07-06 08:39:59,669 INFO    SenderThread:48303 [sender.py:_start_run_threads():818] run started: 1yhv5uf4 with start time 1657121998
2022-07-06 08:39:59,670 DEBUG   SenderThread:48303 [sender.py:send():236] send: summary
2022-07-06 08:39:59,673 INFO    SenderThread:48303 [sender.py:_save_file():952] saving file wandb-summary.json with policy end
2022-07-06 08:39:59,674 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: check_version
2022-07-06 08:39:59,822 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: run_start
2022-07-06 08:40:00,673 INFO    Thread-7  :48303 [dir_watcher.py:_on_file_created():269] file/dir created: /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_083958-1yhv5uf4/files/wandb-summary.json
2022-07-06 08:40:01,461 DEBUG   HandlerThread:48303 [meta.py:__init__():35] meta init
2022-07-06 08:40:01,462 DEBUG   HandlerThread:48303 [meta.py:__init__():49] meta init done
2022-07-06 08:40:01,462 DEBUG   HandlerThread:48303 [meta.py:probe():209] probe
2022-07-06 08:40:01,472 DEBUG   HandlerThread:48303 [git.py:repo():29] git repository is invalid
2022-07-06 08:40:01,472 DEBUG   HandlerThread:48303 [meta.py:_save_pip():53] save pip
2022-07-06 08:40:01,478 DEBUG   HandlerThread:48303 [meta.py:_save_pip():67] save pip done
2022-07-06 08:40:01,479 DEBUG   HandlerThread:48303 [meta.py:probe():247] probe done
2022-07-06 08:40:01,498 DEBUG   SenderThread:48303 [sender.py:send():236] send: files
2022-07-06 08:40:01,499 INFO    SenderThread:48303 [sender.py:_save_file():952] saving file wandb-metadata.json with policy now
2022-07-06 08:40:01,532 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: stop_status
2022-07-06 08:40:01,533 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: stop_status
2022-07-06 08:40:01,542 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: pause
2022-07-06 08:40:01,542 INFO    HandlerThread:48303 [handler.py:handle_request_pause():695] stopping system metrics thread
2022-07-06 08:40:01,664 DEBUG   SenderThread:48303 [sender.py:send():236] send: telemetry
2022-07-06 08:40:01,675 INFO    Thread-7  :48303 [dir_watcher.py:_on_file_created():269] file/dir created: /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_083958-1yhv5uf4/files/wandb-metadata.json
2022-07-06 08:40:01,676 INFO    Thread-7  :48303 [dir_watcher.py:_on_file_created():269] file/dir created: /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_083958-1yhv5uf4/files/requirements.txt
2022-07-06 08:40:01,678 INFO    Thread-7  :48303 [dir_watcher.py:_on_file_created():269] file/dir created: /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_083958-1yhv5uf4/files/output.log
2022-07-06 08:40:01,680 DEBUG   SenderThread:48303 [sender.py:send():236] send: stats
2022-07-06 08:40:02,023 INFO    Thread-11 :48303 [upload_job.py:push():138] Uploaded file /tmp/tmptxh638q7wandb/2uqn81r7-wandb-metadata.json
2022-07-06 08:40:16,667 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: stop_status
2022-07-06 08:40:16,667 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: stop_status
2022-07-06 08:40:30,702 INFO    Thread-7  :48303 [dir_watcher.py:_on_file_modified():286] file/dir modified: /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_083958-1yhv5uf4/files/config.yaml
2022-07-06 08:40:31,797 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: stop_status
2022-07-06 08:40:31,797 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: stop_status
2022-07-06 08:40:46,919 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: stop_status
2022-07-06 08:40:46,920 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: stop_status
2022-07-06 08:41:02,046 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: stop_status
2022-07-06 08:41:02,047 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: stop_status
2022-07-06 08:41:09,044 WARNING MainThread:48303 [internal.py:wandb_internal():153] Internal process interrupt: 1
2022-07-06 08:41:09,151 DEBUG   SenderThread:48303 [sender.py:send():236] send: telemetry
2022-07-06 08:41:09,747 DEBUG   SenderThread:48303 [sender.py:send():236] send: exit
2022-07-06 08:41:09,747 INFO    SenderThread:48303 [sender.py:send_exit():372] handling exit code: 0
2022-07-06 08:41:09,749 INFO    SenderThread:48303 [sender.py:send_exit():374] handling runtime: 1
2022-07-06 08:41:09,754 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: poll_exit
2022-07-06 08:41:09,756 INFO    SenderThread:48303 [sender.py:_save_file():952] saving file wandb-summary.json with policy end
2022-07-06 08:41:09,757 INFO    SenderThread:48303 [sender.py:send_exit():380] send defer
2022-07-06 08:41:09,758 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: poll_exit
2022-07-06 08:41:09,759 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: defer
2022-07-06 08:41:09,759 INFO    HandlerThread:48303 [handler.py:handle_request_defer():163] handle defer: 0
2022-07-06 08:41:09,760 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: defer
2022-07-06 08:41:09,760 INFO    SenderThread:48303 [sender.py:send_request_defer():389] handle sender defer: 0
2022-07-06 08:41:09,760 INFO    SenderThread:48303 [sender.py:transition_state():393] send defer: 1
2022-07-06 08:41:09,761 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: defer
2022-07-06 08:41:09,761 INFO    HandlerThread:48303 [handler.py:handle_request_defer():163] handle defer: 1
2022-07-06 08:41:09,762 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: defer
2022-07-06 08:41:09,762 INFO    SenderThread:48303 [sender.py:send_request_defer():389] handle sender defer: 1
2022-07-06 08:41:09,763 INFO    SenderThread:48303 [sender.py:transition_state():393] send defer: 2
2022-07-06 08:41:09,764 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: defer
2022-07-06 08:41:09,764 INFO    HandlerThread:48303 [handler.py:handle_request_defer():163] handle defer: 2
2022-07-06 08:41:09,765 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: defer
2022-07-06 08:41:09,765 INFO    SenderThread:48303 [sender.py:send_request_defer():389] handle sender defer: 2
2022-07-06 08:41:09,766 INFO    SenderThread:48303 [sender.py:transition_state():393] send defer: 3
2022-07-06 08:41:09,767 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: defer
2022-07-06 08:41:09,768 INFO    HandlerThread:48303 [handler.py:handle_request_defer():163] handle defer: 3
2022-07-06 08:41:09,768 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: defer
2022-07-06 08:41:09,769 INFO    SenderThread:48303 [sender.py:send_request_defer():389] handle sender defer: 3
2022-07-06 08:41:09,769 INFO    SenderThread:48303 [sender.py:transition_state():393] send defer: 4
2022-07-06 08:41:09,770 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: defer
2022-07-06 08:41:09,770 INFO    HandlerThread:48303 [handler.py:handle_request_defer():163] handle defer: 4
2022-07-06 08:41:09,771 DEBUG   SenderThread:48303 [sender.py:send():236] send: summary
2022-07-06 08:41:09,775 INFO    SenderThread:48303 [sender.py:_save_file():952] saving file wandb-summary.json with policy end
2022-07-06 08:41:09,776 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: defer
2022-07-06 08:41:09,776 INFO    SenderThread:48303 [sender.py:send_request_defer():389] handle sender defer: 4
2022-07-06 08:41:09,777 INFO    SenderThread:48303 [sender.py:transition_state():393] send defer: 5
2022-07-06 08:41:09,778 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: defer
2022-07-06 08:41:09,778 INFO    HandlerThread:48303 [handler.py:handle_request_defer():163] handle defer: 5
2022-07-06 08:41:09,779 DEBUG   SenderThread:48303 [sender.py:send_request():250] send_request: defer
2022-07-06 08:41:09,779 INFO    SenderThread:48303 [sender.py:send_request_defer():389] handle sender defer: 5
2022-07-06 08:41:09,861 DEBUG   HandlerThread:48303 [handler.py:handle_request():140] handle_request: poll_exit
2022-07-06 08:41:09,918 ERROR   SenderThread:48303 [internal_api.py:execute():161] 409 response executing GraphQL.
2022-07-06 08:41:09,918 ERROR   SenderThread:48303 [internal_api.py:execute():162] {"errors":[{"message":"Error 1062: Duplicate entry '1104810-1yhv5uf4' for key 'PRIMARY'","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2022-07-06 08:41:10,744 INFO    Thread-7  :48303 [dir_watcher.py:_on_file_modified():286] file/dir modified: /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_083958-1yhv5uf4/files/wandb-summary.json
2022-07-06 08:41:10,772 INFO    WriterThread:48303 [datastore.py:close():279] close: /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_083958-1yhv5uf4/run-1yhv5uf4.wandb
2022-07-06 08:41:10,862 INFO    HandlerThread:48303 [handler.py:finish():806] shutting down handler
2022-07-06 08:41:10,862 ERROR   MainThread:48303 [internal.py:wandb_internal():165] Thread SenderThread:
Traceback (most recent call last):
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 1341, in upsert_run
    response = self.gql(mutation, variable_values=variable_values, **kwargs)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/lib/retry.py", line 108, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/internal_api.py", line 158, in execute
    return self.client.execute(*args, **kwargs)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/internal.py", line 310, in _process
    self._sm.send(record)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/sender.py", line 238, in send
    send_handler(record)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/sender.py", line 252, in send_request
    send_handler(record)
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/sender.py", line 412, in send_request_defer
    self.debounce()
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/sender.py", line 321, in debounce
    self._debounce_config()
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/sdk/internal/sender.py", line 328, in _debounce_config
    name=self._run.run_id, config=config_value_dict, **self._api_settings
  File "/nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/envs/project/lib64/python3.6/site-packages/wandb/apis/normalize.py", line 27, in wrapper
    raise CommError(err.response, err)
wandb.errors.CommError: <Response [409]>
2022-07-06 08:41:12,929 INFO    MainThread:48303 [internal.py:handle_exit():80] Internal process exited
