2022-07-06 09:27:50,741 INFO    MainThread:53688 [wandb_setup.py:_flush():76] Configure stats pid to 53688
2022-07-06 09:27:50,741 INFO    MainThread:53688 [wandb_setup.py:_flush():76] Loading settings from /nfs/stak/users/noelt/.config/wandb/settings
2022-07-06 09:27:50,743 INFO    MainThread:53688 [wandb_setup.py:_flush():76] Loading settings from /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/settings
2022-07-06 09:27:50,744 INFO    MainThread:53688 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-07-06 09:27:50,745 INFO    MainThread:53688 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-07-06 09:27:50,746 INFO    MainThread:53688 [wandb_init.py:_log_setup():461] Logging user logs to /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_092750-12anxiff/logs/debug.log
2022-07-06 09:27:50,747 INFO    MainThread:53688 [wandb_init.py:_log_setup():462] Logging internal logs to /nfs/stak/users/noelt/Documents/Project/Large_Margin_Loss_PyTorch-master/wandb/run-20220706_092750-12anxiff/logs/debug-internal.log
2022-07-06 09:27:50,749 INFO    MainThread:53688 [wandb_init.py:init():495] calling init triggers
2022-07-06 09:27:50,750 INFO    MainThread:53688 [wandb_init.py:init():499] wandb.init called with sweep_config: {}
config: {}
2022-07-06 09:27:50,751 INFO    MainThread:53688 [wandb_init.py:init():515] re-initializing run, found existing run on stack: 10w0eom6
2022-07-06 09:27:50,755 INFO    MainThread:53688 [wandb_run.py:_finish():1680] finishing run tnoel20/Thomas-Masters-Project/10w0eom6
2022-07-06 09:27:50,756 INFO    MainThread:53688 [jupyter.py:save_history():435] not saving jupyter history
2022-07-06 09:27:50,757 INFO    MainThread:53688 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-07-06 09:27:50,758 INFO    MainThread:53688 [wandb_init.py:_jupyter_teardown():393] cleaning up jupyter logic
2022-07-06 09:27:50,758 INFO    MainThread:53688 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-07-06 09:27:50,758 INFO    MainThread:53688 [wandb_run.py:_restore():1834] restore
2022-07-06 09:27:51,364 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2022-07-06 09:27:51,535 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2022-07-06 09:27:51,731 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2022-07-06 09:27:52,128 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 6278
}

2022-07-06 09:27:52,231 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 6278
}

2022-07-06 09:27:52,335 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6278
  total_bytes: 6278
}

2022-07-06 09:27:52,438 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6278
  total_bytes: 6278
}

2022-07-06 09:27:52,541 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6278
  total_bytes: 6278
}

2022-07-06 09:27:52,644 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6278
  total_bytes: 6278
}

2022-07-06 09:27:52,747 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6278
  total_bytes: 6278
}

2022-07-06 09:27:53,100 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6278
  total_bytes: 6278
}

2022-07-06 09:27:53,461 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 6278
  total_bytes: 6278
}
local_info {
}

2022-07-06 09:27:54,628 INFO    MainThread:53688 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-07-06 09:27:54,629 INFO    MainThread:53688 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-07-06 09:27:54,640 INFO    MainThread:53688 [wandb_run.py:_footer_sync_info():3055] logging synced files
2022-07-06 09:27:54,651 INFO    MainThread:53688 [wandb_init.py:init():548] starting backend
2022-07-06 09:27:54,652 INFO    MainThread:53688 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-07-06 09:27:54,656 INFO    MainThread:53688 [backend.py:ensure_launched():217] starting backend process...
2022-07-06 09:27:54,701 INFO    MainThread:53688 [backend.py:ensure_launched():222] started backend process with pid: 54004
2022-07-06 09:27:54,703 INFO    MainThread:53688 [wandb_init.py:init():558] backend started and connected
2022-07-06 09:27:54,712 INFO    MainThread:53688 [wandb_run.py:_label_probe_notebook():1084] probe notebook
2022-07-06 09:27:54,712 INFO    MainThread:53688 [wandb_run.py:_label_probe_notebook():1094] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-07-06 09:27:54,712 INFO    MainThread:53688 [wandb_init.py:init():634] updated telemetry
2022-07-06 09:27:54,839 INFO    MainThread:53688 [wandb_init.py:init():666] communicating run to backend with 30 second timeout
2022-07-06 09:27:56,101 INFO    MainThread:53688 [wandb_run.py:_on_init():1919] communicating current version
2022-07-06 09:27:56,255 INFO    MainThread:53688 [wandb_run.py:_on_init():1923] got version response 
2022-07-06 09:27:56,255 INFO    MainThread:53688 [wandb_init.py:init():700] starting run threads in backend
2022-07-06 09:27:56,313 INFO    MainThread:53688 [wandb_run.py:_console_start():1893] atexit reg
2022-07-06 09:27:56,315 INFO    MainThread:53688 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.WRAP
2022-07-06 09:27:56,315 INFO    MainThread:53688 [wandb_run.py:_redirect():1803] Wrapping output streams.
2022-07-06 09:27:56,317 INFO    MainThread:53688 [wandb_run.py:_redirect():1827] Redirects installed.
2022-07-06 09:27:56,317 INFO    MainThread:53688 [wandb_init.py:init():732] run started, returning control to user process
2022-07-06 09:28:12,155 INFO    MainThread:53688 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 0
2022-07-06 09:28:12,157 INFO    MainThread:53688 [wandb_run.py:_restore():1834] restore
2022-07-06 09:28:12,966 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2022-07-06 09:28:13,130 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2022-07-06 09:28:13,307 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 717
}

2022-07-06 09:28:14,185 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 5056
}

2022-07-06 09:28:14,288 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 717
  total_bytes: 5083
}

2022-07-06 09:28:14,390 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5083
  total_bytes: 5083
}

2022-07-06 09:28:14,493 INFO    MainThread:53688 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5083
  total_bytes: 5083
}

